
# Example of a GET request
GET http://localhost:5000/api/cars

###

# Example of a GET request
GET http://localhost:5000/api/roles

###

# Example of a POST request with JSON body
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "JohnDoePassword123"
}

### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe",
    "email": "johndoe@example.com",
    "password": "JohnDoePassword123",
    "country": "USA",
    "mobile": "1234567890"
}
###

